
name: Docker

on:
  workflow_call:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ vars.USER_DOCKER_HUB }}
        password: ${{ secrets.PASSWORD_DOCKER_HUB }}
    
    - name: Setup Docker Build
      uses: docker/setup-buildx-action@v3.7.1
      
    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.1.8
      with:
        name: GitHubActionsProject-Release  
        path: src/BuildArtifacts/  

    - name: Build and push Docker images
      uses: docker/build-push-action@v6.10.0
      with:

        context: .
        # Path to the Dockerfile
        file: ./DockerFile
        # List of metadata for an image
        push: true
        
        # List of tags
        tags: anthonnylac-git_hub_actions_project_ci:${{ github.ref_name }}
            

