
name: Docker

on:
  workflow_call:

jobs:
  docker:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.USER_DOCKER_HUB }}
        password: ${{ secrets.PASSWORD_DOCKER_HUB }}

    - name: Setup Docker Build
      uses: docker/setup-buildx-action@v3.7.1

