name: Continuous Delivery

on:
  workflow_call: 

jobs:
  EC2:
    runs-on: ubuntu-latest 

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.1.8
      with:
        name: GitHubActionsProject-Release  
        path: src/BuildArtifacts/  

    - name: Deploy server
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: /home/${{ secrets.REMOTE_TARGET }}
        EXCLUDE: "/src/GitHubActionsProject.API/Migrations/"

    - name: executing remote ssh commands using key
      uses: appleboy/ssh-action@v1.2.0
      with:
        host:  ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          export ConnectionStrings_DefaultConnection=${{ secrets.CONNECTIONSTRINGS_DEFAULTCONNECTION }}
      
      
